# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    
    - name: Get Changed Files
      uses: lots0logs/gh-action-get-changed-files@2.0.6
      with:
        token: ${{secrets.GITHUB_TOKEN}}

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}

    #Sees where I am
    - name: See what changed
      run: node concept.js

    #- uses: EndBug/add-and-commit@v4
    #  with:
    #    add: '.'
    #    commit: 'commit JSON files'
    #  env:
    #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}